export declare const SHARED_PORTFOLIO_COLLECTION = "portfolio";
export declare const SHARED_PORTFOLIO_DOC_ID = "app";
export declare function getRequiredFirebaseDb(): import("@firebase/firestore").Firestore;
export declare function getSharedPortfolioDocRef(): import("@firebase/firestore").DocumentReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedAssetsCollectionRef(): import("@firebase/firestore").CollectionReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedPriceReviewsCollectionRef(): import("@firebase/firestore").CollectionReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedAccountPrincipalsCollectionRef(): import("@firebase/firestore").CollectionReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedAccountCashFlowsCollectionRef(): import("@firebase/firestore").CollectionReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedAnalysisCacheDocRef(snapshotHash: string): import("@firebase/firestore").DocumentReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedPortfolioSnapshotsCollectionRef(): import("@firebase/firestore").CollectionReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
export declare function getSharedAssetPriceHistoryCollectionRef(assetId: string): import("@firebase/firestore").CollectionReference<import("@firebase/firestore").DocumentData, import("@firebase/firestore").DocumentData>;
